### ISSUE TITLE
[runix/pgadmin] /var/lib/pgadmin/sessions gets too big and crashes the server

### ISSUE THREAD

**Issue by anita-steiner** [rowanruseler/helm-charts#108]
**Describe the bug**
If you start pgadmin, each liveness/readiness probe will create a session in the /var/lib/pgadmin/sessions folder. After some time the volume is full and you get the error "No space left"

**Version of Helm and Kubernetes**:
Helm: v3.6.1
Kubernetes: 1.20

**Which chart**:
pgadmin4: 1.6.8
image: dpage/pgadmin4:5.4

**What happened**:
Each liveness probe will create a session in the /var/lib/pgadmin/sessions folder til the folder is full. The liveness probe path is /misc/ping

**What you expected to happen**:
Liveness/readiness probe shouldn't create a session

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
Interesting, I thought this was resolved a while ago when the livenessProbe path /misc/ping was used. If I search the history of this bug it would have been resolved around 2018 when it was reported again. Perhaps it got reintroduced.

https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=commitdiff;h=82d77c4608b92304c7737ec4a3d5ab331efd82e9

I'll see if somebody already reported it at pgadmin, perhaps it got already resolved in a version upgrade.

Thanks for reporting, but this is sadly pgadmin itself.

**Comment by rowanruseler** [comment]
@anita-steiner I am unable to reproduce this issue, are you still experiencing it?

**Comment by hmoravec** [comment]
@rowanruseler I'm am experience this issue periodically. After a few weeks or running I have to manually delete `/var/lib/pgadmin/sessions` and restart the pod. I'm using this Helm chart in version 1.7.0 with image `pgadmin4:5.6`.

**Comment by codezork** [comment]
same with me

**Comment by rowanruseler** [comment]
Can you guys see if this still occurs with higher chart versions?

I am not sure in what version I've added it, but this was added to the livenessProbe and readinessProbe a while ago:
```
httpGet:
  port: http
  {{- if .Values.env.contextPath }}
  path: "{{ .Values.env.contextPath }}/misc/ping"
  {{- else }}
  path: /misc/ping
  {{- end }}
```

and that should resolve the issue described.

**Comment by hmoravec** [comment]
@rowanruseler Unfortunately, the fix you mentioned was already present in version 1.7.0 where I encountered the problem: https://github.com/rowanruseler/helm-charts/blame/master/charts/pgadmin4/templates/deployment.yaml#L73-L93

**Comment by hmoravec** [comment]
But I upgraded recently to version 1.8.2 and I've checked `/var/lib/pgadmin/sessions` folder now and it is almost empty which looks promising.
