### ISSUE TITLE
[pgadmin4] How to restrict Github Oauth2 to a specific Github Organization name

### ISSUE THREAD

**Issue by waterdrop01** [rowanruseler/helm-charts#110]
Hello,

PGAGMIN 5.5 add [OAUTH2](https://www.pgadmin.org/docs/pgadmin4/5.5/oauth2.html) support.

Is there a way to enable it in the `values.yml`?

What would be nice would be to allow custom config to be defined in values.yml

Thanks!

**Comment by waterdrop01** [comment]
I think I found my answer here => https://github.com/rowanruseler/helm-charts/pull/81/files

Any idea how I can restrict Github Oauth2 to a specific Github Organization name? To allow only users part of a specific github org to login into PGADMIN.

Thanks !

**Comment by rowanruseler** [comment]
Closing this issue since an oauth2 example has been merged a while back and should sustain enough information. If not, please create a net ticket.
