### ISSUE TITLE
LDAP or AD Authentication

### ISSUE THREAD

**Issue by wildhi** [rowanruseler/helm-charts#113]
Hello,
it´s possible to use LDAP or AD  to Authenticate Users in pgadmin ?
Or how can I change the AUTHENTICATION_SOURCES in the config.py in the container?

**Comment by ronaldjeden** [comment]
Hi wildhi. I also am having issues with LDAP. I tried to add to add the following parameters in the values yaml we have in a stand alone pgadmin4 installation but without luck.

VolumePermissions:
  enabled: true
env:
  variables:
  - name: PGADMIN_LISTEN_ADDRESS
    value: 0.0.0.0
  - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
    value: "['ldap', 'internal']"
  - name: PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
    value: "True"
  - name: PGADMIN_CONFIG_LDAP_CONNECTION_TIMEOUT
    value: 10
  - name: PGADMIN_CONFIG_LDAP_ANONYMOUS_BIND
  - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
  - name: PGADMIN_CONFIG_LDAP_SERVER_URI
    value: "'ldap://internalserver:389'"
  - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
    value: "'ou=User,ou=Accounts,ou=UserManagement,dc=xxx,dc=xxx,dc=xx'"
  - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
    value: "'sAMAccountName'"
  - name: PGADMIN_CONFIG_LDAP_BIND_USER
    value: "'CN=xxxx'"
  - name: PGADMIN_CONFIG_LDAP_SEARCH_FILTER
    value: "'(cn={})'"
  - name: PGADMIN_CONFIG_LDAP_SEARCH_SCOPE
    value: "'SUBTREE'"
  - name: PGADMIN_CONFIG_LDAP_USE_STARTTLS
    value: "False"
