### ISSUE TITLE
Paths works only with path:

### ISSUE THREAD

**Issue by vaisov** [rowanruseler/helm-charts#120]
I was getting error:

```
Error: template: pgadmin4/templates/ingress.yaml:38:21: executing "pgadmin4/templates/ingress.yaml" at <.path>: can't evaluate field path in type interface {}
helm.go:81: [debug] template: pgadmin4/templates/ingress.yaml:38:21: executing "pgadmin4/templates/ingress.yaml" at <.path>: can't evaluate field path in type interface {}
```

To fix that I've changed this:
https://github.com/rowanruseler/helm-charts/blob/12379ad4d17d27fe86217bc295b0a1eb099a3a59/charts/pgadmin4/examples/enable-ldap-integration.yaml#L37

to:
```
      paths:
        - path: /
```

Not sure if that's my issue only.

**Comment by rowanruseler** [comment]
@vaisov this is actually an issue I created. I used to not have this specific setup, but I wanted to match the default helm3 chart more so I implemented it but forgot to increase the version to a major upgrade so a lot of people missed it.

Apologies for the inconvenience.
