### ISSUE TITLE
Github example does not work for oauth2 - An email id is required to login into pgAdmin

### ISSUE THREAD

**Issue by cep21** [rowanruseler/helm-charts#139]
I've copied the example for github.  I get this error in the logs after authenticating

```
2022-03-06 19:03:51,153: ERROR  pgadmin:        An email id is required to login into pgAdmin. Please update your Oauth2 profile.
NoneType: None
```

**Comment by rowanruseler** [comment]
I am not 100% sure, since this part was implemented by somebody else - and I've not yet come around playing with oauth2 myself. But I think it is because it misses 'OAUTH2_SCOPE': within the configuration.

Please check pgAdmins documentation on OAUTH, on what is actually required.
