### ISSUE TITLE
Add LDAP support

### ISSUE THREAD

**Issue by KIRY4** [rowanruseler/helm-charts#15]
Add LDAP support to the chart (currently pgadmin uses default credentials)

**Comment by rowanruseler** [comment]
@KIRY4 Could you give me documentation examples of this specific method?

Cause you are currently able to adjust the pgadmin credentials within the values file. Perhaps I am not fully understanding your request.

**Comment by KIRY4** [comment]
@rowanruseler Hello!

https://www.pgadmin.org/docs/pgadmin4/development/config_py.html - LDAP Configuration section in config.py.

For example we have LDAP integration in stable/grafana - https://github.com/helm/charts/blob/master/stable/grafana/values.yaml - ## Grafana's LDAP configuration section.

It will be cool if we will have the same approach for pgadmin. Thanks!

**Comment by rowanruseler** [comment]
@KIRY4 seems doable, if I read the docker image:
> PGADMIN_CONFIG_
> This is a variable prefix that can be used to override any of the configuration options in pgAdmin’s config.py file.

So in this cause we would need:
* PGADMIN_CONFIG_AUTHENTICATION_SOURCES
* PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
* PGADMIN_CONFIG_LDAP_CONNECTION_TIMEOUT
* PGADMIN_CONFIG_LDAP_SERVER_URI
* PGADMIN_CONFIG_LDAP_BASE_DN
* PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
* PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
* PGADMIN_CONFIG_LDAP_SEARCH_FILTER
* PGADMIN_CONFIG_LDAP_SEARCH_SCOPE
* PGADMIN_CONFIG_LDAP_USE_STARTTLS
* PGADMIN_CONFIG_LDAP_CA_CERT_FILE
* PGADMIN_CONFIG_LDAP_CERT_FILE
* PGADMIN_CONFIG_LDAP_KEY_FILE

Did I miss any?

I don't run LDAP myself, so I won't be able to confirm if it works. If I build a branch can you test it out for me and show it functioning?

**Comment by rowanruseler** [comment]
Actually, this would be resolved once https://github.com/rowanruseler/helm-charts/pull/14/files is merged. Just awaiting the pull requester to sign his/her pull request.

**Comment by KIRY4** [comment]
@rowanruseler both options are ok for me. Looks like it will be signed in few hours/days so I can wait...

**Comment by rowanruseler** [comment]
@KIRY4 just merged that pull request, and it should be possible to now implement LDAP as you desired. Good luck, let me know if it didn't work.
