### ISSUE TITLE
How to create the pgpass file secret?

### ISSUE THREAD

**Issue by tonsV2** [rowanruseler/helm-charts#150]
I'm a bit confused by the below example.

https://github.com/rowanruseler/helm-charts/blob/master/charts/pgadmin4/examples/add-pgpass-file.yaml

Am I supposed to create the secret manually? Or does this chart contain functionality to do so?

**Comment by rowanruseler** [comment]
There a two things, one is the env.email and env.password for the initial login. The second is that, the connections to the primary database might also require login credentials. Those can be added by the pgpass-file.
