### ISSUE TITLE
[pgadmin4] Chart Version 1.10 deploys wrong image tag

### ISSUE THREAD

**Issue by schnapsidee** [rowanruseler/helm-charts#156]
**Describe the bug**
Version 1.10 of the pgadmin Chart deploys the image Version 6.1 instead of 6.10

**Anything else we need to know**:
This happens because the AppVersion in your Chart.yaml is a float and not a string. 
The trailing 0 gets removed for floats and helm generates a manifest with image version 6.1. 
Helm docs reccomend a string: "appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended."

I did a quick dry-run and Helm doesn't have any issues with the image if AppVersion is a string, it generates the image string as intended: 

image: "docker.io/dpage/pgadmin4:6.10"

**Comment by rowanruseler** [comment]
Apologies! Thanks for pointing this out.
