### ISSUE TITLE
[pgadmin4] Stop using initContainer

### ISSUE THREAD

**Issue by krezovic** [rowanruseler/helm-charts#17]
**Describe the bug**

I'm trying to run pgadmin4 inside a very restricted kubernetes environment (company internal). The environment prohibits executing anything as root. Init container has "runAsUser: 0" hardcoded.

What it does is simply chown the runtime directory to the correct user. However, I have found out that this is unnecessary, since fsGroup inside POD security context ensures that the runtime directory is writable by the correct GID.

I've removed initContainer block entirely, pgadmin4 was able to start and it works as expected.

**Version of Helm and Kubernetes**:

3.2.0/1.16.x

**Which chart**:

pgadmin4

**What happened**:

POD never started due to restriction.

**What you expected to happen**:

For POD to start.

**How to reproduce it** (as minimally and precisely as possible):

Try to install it on an environment that prohibits running anything as root. Not sure if there's such environment publicly available.

**Comment by rowanruseler** [comment]
Without the initContainer the following error occurs:
```WARNING: Failed to set ACL on the directory containing the configuration database: [Errno 1] Operation not permitted: '/var/lib/pgadmin'```

**Comment by krezovic** [comment]
And what would we lose if the setfacl fails? I did see this, but it's a WARNING not ERROR or SEVERE, so I chose to ignore it.

**Comment by rowanruseler** [comment]
Well, at the current moment we lose nothing. I also tested it today, and it seems to be fully working. In the past this was an error and it would fail, I think that was version 4.15 if not mistaken.

I'll make a small PR tomorrow with the function to enable initContainer if desired but by default I'll disable it. Agreed?

**Comment by krezovic** [comment]
Your propsed solution is fine to me. Thanks for consideration.

**Comment by rowanruseler** [comment]
@krezovic perhaps you would have a moment to check out my pull request: https://github.com/rowanruseler/helm-charts/pull/18
