### ISSUE TITLE
Helm chart repo inaccessible

### ISSUE THREAD

**Issue by LedAlex** [rowanruseler/helm-charts#171]
Helm chart repo at https://helm.runix.net/ returns 404.
![image](https://user-images.githubusercontent.com/27248144/194459805-1749b6ce-01bf-4953-bf94-b91e7b5db326.png)

**Comment by LedAlex** [comment]
Repo and index.yaml now is accessible.

**Comment by MHenn1g** [comment]
Somehow this problem does not seem to be fixed, could you please look into it again?
