### ISSUE TITLE
Faild to mount definitions , can't find the key servers.json

### ISSUE THREAD

**Issue by anieo** [rowanruseler/helm-charts#182]
**Describe the bug**
deployment fails when you use helm server definitions and existingSecret 

**Version of Helm and Kubernetes**:
kubernetes v1.23.7
helm : v3.9.0"

**Which chart**:
pgadmin4

**What happened**:

when using existingSecret to specify password secret and secret key you you have to specify `key: servers.json` which is not mentioned anywhere 
even when i used 

```
serverDefinitions:
  enabled: true
```

**What you expected to happen**:

when using helm value `serverDefinitions.enable: true ` i should need to provide `key: servers.json` in my credential secret 
OR `secretKeys:` need to have the value to specify the name of the key and it needs to be optional 
and both options need to optional

**How to reproduce it** (as minimally and precisely as possible):

1- define your password in a secret
2- specify the secret in your helm chart
```
existingSecret: SECRET
secretKeys:
  pgadminPasswordKey: SECRET_KEY
``` 
3-define server definition in the helm chart
```

serverDefinitions:
  enabled: true
  servers: 
    firstServer:
      Name : "K8S  Postgres"
      Group : "Servers"
      Port : 5432
      Username : "postgres
      HOST : "postgresql"
      SSLMode : "prefer"
      MaintenanceDB : "postgres"
```
**Anything else we need to know**:
no Thank you for your work

**Comment by bryanwieg** [comment]
I've run into the same issue, the cause is here:
https://github.com/rowanruseler/helm-charts/blob/d239eb380f3f49e3049b00ef8683a60ed6d9a32e/charts/pgadmin4/templates/secrets.yaml

**Comment by ViliusS** [comment]
Same here. Not sure what is the reason to have password and servers.json file in the same secret, but this breaks things.

**Comment by dkpat12** [comment]
+1  It's really annoying that we can't use both serverDefinitions and an externally defined password

**Comment by rowanruseler** [comment]
https://github.com/rowanruseler/helm-charts/pull/211 should resolve this issue.
