### ISSUE TITLE
[runix/pgadmin4] custom command doesn't accept arguments

### ISSUE THREAD

**Issue by splix** [rowanruseler/helm-charts#185]
When you want to use a custom command you cannot use any arguments.

I.e. the following does not work:
```
command: ["sh","-c","sleep infinity"]
```

But a command without arguments is fine:
```
command: ["top"]
```

The reason is that it's threaten as a _string_ so cannot find an executable with spaces.

**Comment by rowanruseler** [comment]
You can try the following then instead:
```
command: ["sh"]
args: ["-c", "sleep", "infinity"]
```

**Comment by splix** [comment]
hm, I should try this. I just don't see how it would be handled in the template in this case and nothing in the docs, so I didn't try
