### ISSUE TITLE
pgadmin4 helm chart shouldn't require ingress secretName

### ISSUE THREAD

**Issue by rustygreen** [rowanruseler/helm-charts#189]
**Describe the bug**
When setting an ingress value in the helm values, if you don't set a `secretName`, an error is thrown.

![image](https://user-images.githubusercontent.com/1774477/213807415-91e0a03d-2354-4916-9663-afbdf9467290.png)

**Version of Helm and Kubernetes**:
Kubernetes: v1.26.0+k3s1
Helm: latest

**Which chart**:
pgadmin4

**What happened**:

An error is thrown if you don't set a `secretName` with ingress enabled.

**What you expected to happen**:

An error should not be thrown. It is valid to use ingress without a secretName (for example, when it is desired for ingress to use the default certificate)

**How to reproduce it** (as minimally and precisely as possible):

Configure ingress in the helm values without defining a secretName

**Comment by rowanruseler** [comment]
@rustygreen would this resolve your issue: https://github.com/rowanruseler/helm-charts/pull/190 ?

**Comment by rowanruseler** [comment]
@rustygreen merged, please `helm dep update` and try again and let me know :) cheers!

**Comment by chlumper** [comment]
> 

the fix introduced an new issue #191 
i provided a PR #192 which should solve the problem
