### ISSUE TITLE
Ability to set MAX LOGIN ATTEMPTS 

### ISSUE THREAD

**Issue by shyam-ks** [rowanruseler/helm-charts#199]
Ability to set MAX LOGIN ATTEMPTS as the currently 3 wrong login attempts locks the application

**Comment by rowanruseler** [comment]
This is the repo that is using the pgadmin4 docker container, if it is not configurable with env variables: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html#environment-variables - you can request it here: https://github.com/pgadmin-org/pgadmin4
