### ISSUE TITLE
Bitnami Kubeapps not able to show deployed pgadmin4 chart

### ISSUE THREAD

**Issue by frankvollenweider** [rowanruseler/helm-charts#21]
Hi @rowanruseler ,

I deployed pgadmin4 through bitnami's kubeapps into my gke cluster. The deployment was successfull but kubeapps is now not able to show the deployed pgadmin4.

I opened an issue in the kubeapps repository and it might be interesting for you to have a look at it:
https://github.com/kubeapps/kubeapps/issues/1725

The problem is, that the library they use to parse the deployment.yaml is not able to parse line 73 in there: `value: !!string {{ .Values.env.enhanced_cookie_protection }}`

**Comment by rowanruseler** [comment]
@frankvollenweider thanks for informing me about it. Looks like they are implementing a fix soon.

**Comment by frankvollenweider** [comment]
@rowanruseler Yes, they did. They use now another yaml library which ignores unknown tags and falls back to a default. But maybe the type you use in the cast is not supported. Have a look at the warning message:
`YAMLWarning: The tag tag:yaml.org,2002:string is unavailable, falling back to tag:yaml.org,2002:str`
Maybe it should be
`value: !!str {{ .Values.env.enhanced_cookie_protection }}`
instead of
`value: !!string {{ .Values.env.enhanced_cookie_protection }}`

**Comment by rowanruseler** [comment]
@frankvollenweider seems to be it is `!!str` now, I'll test this weekend and if it works I'll merge it. Thanks for the input.

**Comment by rowanruseler** [comment]
@frankvollenweider are you able to test: https://github.com/rowanruseler/helm-charts/pull/23

I've run some local test, and it seems to be functioning, let me know if you could double confirm for me.

**Comment by frankvollenweider** [comment]
@rowanruseler : It looks good. I deployed pgadmin4 chart version 1.2.20 using kubeapps and it works!
Thank you very much!
