### ISSUE TITLE
[pgadmin4] horizontalPodAutoscaler v2beta -> v2

### ISSUE THREAD

**Issue by pww217** [rowanruseler/helm-charts#213]
**Is your feature request related to a problem? Please describe.**

When I try to enable the autoscaler feature in this chart, I get the following error;

```
The Kubernetes API could not find version "v2beta1" of autoscaling/HorizontalPodAutoscaler for requested resource pgadmin/pgadmin-pgadmin4. Version "v2" of autoscaling/HorizontalPodAutoscaler is installed on the destination cluster.
```

**Describe the solution you'd like**

I think it's really as simple as changing the template API version to `v2`

**Describe alternatives you've considered**

Forking and making the change myself, or just not using autoscaling.

**Additional context**

**Comment by rowanruseler** [comment]
@pww217 can you maybe test against my branch here: rr/issues-213/horizontalPodAutoscaler
