### ISSUE TITLE
[pgadmin4] AWS SSO integration with pgadmin

### ISSUE THREAD

**Issue by n1vgabay** [rowanruseler/helm-charts#220]
The only thing I was thinking about and didn't find a way is integrate pgadmin4 with our users associated in our AWS SSO.
Instead of creating local users in the service, I'd prefer taking current google users exists in our SSO.

**Comment by rowanruseler** [comment]
Have you looked at this example?
https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/examples/add-oauth2-config.yaml

**Comment by n1vgabay** [comment]
It was 1 year ago and I already started working with a different company but thanks for your reply anyway!
