### ISSUE TITLE
PGAdmin4 Helm chart- It crashes with QueuePool limit overflow

### ISSUE THREAD

**Issue by rhegde2** [rowanruseler/helm-charts#225]
**Describe the bug**
PGadmin crashes with QueuePool limit overflow

**Version of Helm and Kubernetes**:

```
version: 1.15.4
appVersion: "7.4"
Kubernetes : OKE-1.27.2

```

**Which chart**:
PGAdmin4

**What happened**:

It fails with below error:

{"success":0,"errormsg":"QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)","info":"","result":null,"data":null}

**What you expected to happen**:
It should run and accept the connections. 

**How to reproduce it** (as minimally and precisely as possible):
Looks like a bug. It happens once every 2 weeks. May be some overflow.  If I delete and create the pod then it works for next 2 weeks.

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
Does this also occurs with later pgAdmin4 versions?
