### ISSUE TITLE
[pgadmin4] Common Labels

### ISSUE THREAD

**Issue by Baboulinet-33** [rowanruseler/helm-charts#236]
Hello,

It is possible to add a value `commonLabels` that add labels to all the deployed resources ?
(like in bitnami chart, e.g https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml#L64)

Thanks,
Baptiste

**Comment by rowanruseler** [comment]
@Baboulinet-33 you are more then welcome to open a pull request with this value added, please remember to sign your commit.
