### ISSUE TITLE
[pgadmin4]  namespace name need to quote to support numeric named namespace

### ISSUE THREAD

**Issue by miteshpatelfxt** [rowanruseler/helm-charts#241]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**:
pgadmin4

**What happened**:
we use numeric namespace name
getting this error.

json: cannot unmarshal number into Go struct field ObjectMeta.metadata.namespace of type string.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Thank you.
I tested it locally, just need to add "| quote" in the pgadmin.namespaceName helper function

{{/*
Create the name of the namespace
*/}}
{{- define "pgadmin.namespaceName" -}}
{{- default .Release.Namespace .Values.namespace | quote }}
{{- end }}

**Comment by rowanruseler** [comment]
Hi @miteshpatelfxt, thank you for creating an issue. Please see: https://github.com/rowanruseler/helm-charts/pull/266, and let me know if this fixes your specific issue.
