### ISSUE TITLE
[pgadmin4] add hostAliases feature

### ISSUE THREAD

**Issue by malcolm061990** [rowanruseler/helm-charts#251]
**Is your feature request related to a problem? Please describe.**
Hi. We need to modify /etc/hosts in running pod in this helm chart.

**Describe the solution you'd like**
Add `hostAliases` config to template -  https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/

**Comment by rowanruseler** [comment]
Hi @malcolm061990, thank you for your request.

Could you please test: https://github.com/rowanruseler/helm-charts/pull/264, and let me know if it works as intended for you?

Thank you!

**Comment by malcolm061990** [comment]
Hi @rowanruseler 
thanks for your PR. I don't have ability to test it now but it looks like it must work :)
