### ISSUE TITLE
regarding helm chart

### ISSUE THREAD

**Issue by Hokwang** [rowanruseler/helm-charts#26]
Hi,

I want to use pgadmin helm chart, but
I think https://helm.runix.net has error.

I think that is github pages, but that is empty.

If not, is this my connection problem??

**Comment by Hokwang** [comment]
I think you need index.html

**Comment by rowanruseler** [comment]
@Hokwang apologies for the late reply, but there is no issue at all. It is a repository for helm, so once added you can use helm to see what is in it, e.g.:
```
$ helm search runix                      
NAME          	CHART VERSION	APP VERSION	DESCRIPTION                                                 
runix/pgadmin4	1.2.12       	4.20.0     	pgAdmin4 is a web based administration tool for PostgreSQ...
```

**Comment by Hokwang** [comment]
Hi, sorry for this,
I am behind company proxy.
so can you provide https://rowanruseler.github.io/helm-charts instead of https://helm.runix.net ?

**Comment by rowanruseler** [comment]
@Hokwang if you are behind company proxy, I advice you to clone the repo into your company repo, and release it from there.

**Comment by Hokwang** [comment]
ok. thanks.
