### ISSUE TITLE
pgadmin4 Helm Chart is invalid because of empty subPath

### ISSUE THREAD

**Issue by bguijt** [rowanruseler/helm-charts#261]
**Describe the bug**
When I validate the output of this Helm chart with [Kubeconform](https://github.com/yannh/kubeconform), I get a validation error because of [an empty subPath](https://github.com/rowanruseler/helm-charts/blob/main/charts/pgadmin4/templates/deployment.yaml#L183):
```
volumeMounts:
  - name: pgadmin-data
    mountPath: /var/lib/pgadmin
    subPath: {{ .Values.persistentVolume.subPath | default "" }}
```
Kubeconform publishes this error:
```
problem validating schema. Check JSON formatting: jsonschema: '/spec/template/spec/containers/0/volumeMounts/0/subPath' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/deployment.json#/properties/spec/$ref/properties/template/$ref/properties/spec/$ref/properties/containers/items/$ref/properties/volumeMounts/items/$ref/properties/subPath/type: expected string, but got null
```

**Version of Helm and Kubernetes**:
Helm version: 3.16.1
Kubernetes version: 1.30

**Which chart**:
pgadmin4, 1.29.0

**What you expected to happen**:
I expect to only have `subPath` published when there is an actual value for `persistentVolume.subPath`.

**How to reproduce it** (as minimally and precisely as possible):
```
helm template my-release runix/pgadmin4 \
    | kubeconform -kubernetes-version 1.30.0 \
        -schema-location "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}/{{.ResourceKind}}.json" \
        -summary \
        -output pretty
```
yields the following output:
```
✖ stdin: Deployment my-release-pgadmin4 is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/template/spec/containers/0/volumeMounts/0/subPath' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/deployment.json#/properties/spec/$ref/properties/template/$ref/properties/spec/$ref/properties/containers/items/$ref/properties/volumeMounts/items/$ref/properties/subPath/type: expected string, but got null
Summary: 6 resources found parsing stdin - Valid: 5, Invalid: 1, Errors: 0, Skipped: 0
```

**Workaround**
is to add this value: `persistentVolume.subPath="."`

**Comment by rowanruseler** [comment]
Hi @bguijt, thank you for reporting the bug. Please check out: https://github.com/rowanruseler/helm-charts/pull/265 and let me know if it is still missing anything.
