### ISSUE TITLE
PGAdmin4 - subpath

### ISSUE THREAD

**Issue by bemanuel** [rowanruseler/helm-charts#29]
Permit to define the subPath of pgadmin4 on PVC, this avoid some PVC shared with others APPS on the same namespace

**Comment by rowanruseler** [comment]
Got an example for me?

**Comment by chlumper** [comment]
The following links show an example for `subPath` at the postgresql helm chart:
https://github.com/bitnami/charts/blob/a3c83404c73850f024e927c7809f3c5bdcbc0e04/bitnami/postgresql/values.yaml#L488
https://github.com/bitnami/charts/blob/a3c83404c73850f024e927c7809f3c5bdcbc0e04/bitnami/postgresql/templates/statefulset.yaml#L127

General doc for `subPath`: https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath

As denoted by @bemanuel  it would be handy to have the `subPath` option if a PVC is used multiple times.
