### ISSUE TITLE
helm chart deploy failed

### ISSUE THREAD

**Issue by kerven88** [rowanruseler/helm-charts#36]
1）Environment 
helm version:  helm3
kubernetes version:  v1.17.6

2）deploy
helm install pgadmin runix/pgadmin4 --set env.password=admin --namespace test
kubectl get po,svc -n test |grep pgadmin
![image](https://user-images.githubusercontent.com/51351006/86215049-ab3fa500-bbae-11ea-8691-4e0acdeff5c8.png)

kubectl get logs for pgadmin:
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
[2020-07-01 07:20:22 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-07-01 07:20:22 +0000] [1] [ERROR] Retrying in 1 second.
[2020-07-01 07:20:23 +0000] [1] [ERROR] Retrying in 1 second.
[2020-07-01 07:20:24 +0000] [1] [ERROR] Retrying in 1 second.
[2020-07-01 07:20:25 +0000] [1] [ERROR] Retrying in 1 second.
[2020-07-01 07:20:26 +0000] [1] [ERROR] Retrying in 1 second.
[2020-07-01 07:20:27 +0000] [1] [ERROR] Can't connect to ('::', 80)

Can you tell me what's going on? 
thanks very much!

**Comment by arichardetmc** [comment]
@kerven88 if you are working in an IPv4-only environment, try to uncomment a portion of the [variables](https://github.com/rowanruseler/helm-charts/blob/master/charts/pgadmin4/values.yaml#L146) in the values. It should look like this:
```
variables:
  - name: PGADMIN_LISTEN_ADDRESS
    value: "0.0.0.0"
```

This change got me past what you are seeing above.

**Comment by kerven88** [comment]
> @kerven88 if you are working in an IPv4-only environment, try to uncomment a portion of the [variables](https://github.com/rowanruseler/helm-charts/blob/master/charts/pgadmin4/values.yaml#L146) in the values. It should look like this:
> 
> ```
> variables:
>   - name: PGADMIN_LISTEN_ADDRESS
>     value: "0.0.0.0"
> ```
> 
> This change got me past what you are seeing above.

Uncomment a portion of the variables in the values, it works, tks!
