### ISSUE TITLE
None default env.email and end.password don't work

### ISSUE THREAD

**Issue by pbebbo** [rowanruseler/helm-charts#50]
when setting the email and password for example as:

```bash
pgadmin4:
  env:
    email: test 
    password: test
```

PgAdmin UI doesn't let me log in with those details?

**Comment by rowanruseler** [comment]
I am not really sure why it doesn't work like that, but with the e.g. already in the values it does work for me:

```
env:
  # can be email or nickname
  email: chart@example.local
  password: SuperSecret
```

**Comment by rowanruseler** [comment]
What error are you receiving if you log the pod?

**Comment by pbebbo** [comment]
I'm sorry, I don't have this information and I am not in a position to redeploy to find them. When I am in a position to do this will post them.

**Comment by pbebbo** [comment]
> I am not really sure why it doesn't work like that, but with the e.g. already in the values it does work for me:
> 
> ```
> env:
>   # can be email or nickname
>   email: chart@example.local
>   password: SuperSecret
> ```
In my value.yaml if I don't define these values (`env.email` and `env.password`) these default use work perfect when logging in to the pgadmin UI.

**Comment by pbebbo** [comment]
Wednesday morning does work (uk-time), if that works for you?
Cheers,
PB

**Comment by rowanruseler** [comment]
Just post the logs here, when it fails. I can take a look when I've the time :)

**Comment by pbebbo** [comment]
HI @rowanruseler,

here are the logs:

```bash
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:17:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:18:04 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:18:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:19:04 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:19:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:20:04 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:20:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:21:04 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:21:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:22:04 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET / HTTP/1.1" 302 237 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /login?next=%2F HTTP/1.1" 200 1707 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/js/generated/style.css?ver=42600 HTTP/1.1" 200 86742 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/vendor/require/require.min.js?ver=42600 HTTP/1.1" 200 6340 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/js/generated/pgadmin.style.css?ver=42600 HTTP/1.1" 200 11149 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/js/generated/pgadmin.css?ver=42600 HTTP/1.1" 200 48014 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/js/generated/pgadmin_commons.js?ver=42600 HTTP/1.1" 200 62546 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/js/generated/vendor.others.js?ver=42600 HTTP/1.1" 200 282366 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:27 +0000] "GET /static/js/generated/vendor.main.js?ver=42600 HTTP/1.1" 200 228096 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:28 +0000] "GET /static/img/login.svg?ver=42600 HTTP/1.1" 200 0 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:28 +0000] "GET /static/js/generated/fonts/Roboto-Regular.ttf HTTP/1.1" 200 0 "http://localhost:54002/static/js/generated/pgadmin.style.css?ver=42600" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:29 +0000] "GET /favicon.ico?ver=42600 HTTP/1.1" 302 265 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:29 +0000] "GET /static/favicon.ico?ver=42600 HTTP/1.1" 200 0 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:22:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:40 +0000] "POST /authenticate/login HTTP/1.1" 302 209 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:40 +0000] "GET / HTTP/1.1" 302 237 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:22:40 +0000] "GET /login?next=%2F HTTP/1.1" 200 1978 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:23:04 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:10.0.0.1 - - [16/Oct/2020:07:23:34 +0000] "GET /misc/ping HTTP/1.1" 200 4 "-" "kube-probe/1.17+"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:23:41 +0000] "POST /authenticate/login HTTP/1.1" 302 209 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:23:41 +0000] "GET / HTTP/1.1" 302 237 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
pgadmin
::ffff:127.0.0.1 - - [16/Oct/2020:07:23:41 +0000] "GET /login?next=%2F HTTP/1.1" 200 1978 "http://localhost:54002/login?next=%2F" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36"
```
this is the warning I get in the UI:

![pgAdmin_4](https://user-images.githubusercontent.com/10131113/96225937-c1207c80-0f89-11eb-8209-c59e6c0d800d.jpg)

**Comment by rowanruseler** [comment]
Not really sure what is going on, I think perhaps the alias rather then an email is not really working. As a work-around I advice to use an email for now and I'll see if this bug is because of helm or it is within the container itself in the incoming week. Thanks for reporting it

**Comment by codezork** [comment]
Hi Rowan,
It is the same problem with my installation. I cannot use the admin-secret nor pgpassfile nor env. As soon as env is used in overriding values, no chance to login. If you leave it blank you can use your defaults. Even if you repeat your settings, login is impossible. As a hint my log. It could be some problem with permissions:

`WARNING: Failed to set ACL on the directory containing the configuration database:
           [Errno 1] Operation not permitted: '/var/lib/pgadmin'
HINT   : You may need to manually set the permissions on
         /var/lib/pgadmin to allow pgadmin to write to it.
NOTE: Configuring authentication for SERVER mode.

sudo: setrlimit(RLIMIT_CORE): Operation not permitted
[2020-10-30 22:54:46 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-10-30 22:54:46 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2020-10-30 22:54:46 +0000] [1] [INFO] Using worker: threads
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-10-30 22:54:46 +0000] [90] [INFO] Booting worker with pid: 90
WARNING: Failed to set ACL on the directory containing the configuration database:
           [Errno 1] Operation not permitted: '/var/lib/pgadmin'
HINT   : You may need to manually set the permissions on
         /var/lib/pgadmin to allow pgadmin to write to it.
`

**Comment by rowanruseler** [comment]
@codezork you can resolve that permission error by running VolumePermissions: enabled: true

Maybe it works then, please let me know.

**Comment by codezork** [comment]
Hi, yes the permission issue is gone. But the login credentials still do not work for some reason.

**Comment by HFSVBC** [comment]
I have the same issue, looking at the PGAdmin code, based on the error it seems it can not find the user

**Comment by HFSVBC** [comment]
Correction, I copied the database over to my laptop and checked the user exists. When I tried to run a pgadmin locally with the same database I had the same issue. Maybe it is related to the password.

**Comment by magsoftware** [comment]
I have the same issue here.
APP VERSION: 4.29.0
CHART: pgadmin4-1.4.6

My values.yaml:

```
% cat values.yaml
env:
  # can be email or nickname
  email: admin
  password: SuperSecret
```

Command:

`helm install my-pgadmin4 runix/pgadmin4 -f values.yaml`

And I can not login (I use kubectl port-forward $POD_NAME 8080:80). If I check for env variables:

```
% k exec -it $POD_NAME -- env | grep PGADMIN_DEFAULT
PGADMIN_DEFAULT_PASSWORD=SuperSecret
PGADMIN_DEFAULT_EMAIL=admin
```

they are ok.

Is it maybe port forwarding by kubectl ?

**Comment by JarnoRFB** [comment]
I experience the same problem, it works for me with chart version `1.3.2` though, but fails with the latest version `1.4.6`.

**Comment by rafis** [comment]
@JarnoRFB thank you very much! I have downgraded to `--version 1.3.2` when `helm upgrade --install`ing.

**Comment by rowanruseler** [comment]
> I experience the same problem, it works for me with chart version `1.3.2` though, but fails with the latest version `1.4.6`. Unfortunately the default logs give no hints at all.

Thanks, I can hopefully take a look next week and then compare the charts to see how I broke it. Apologies for the inconvenience.

**Comment by JarnoRFB** [comment]
Could also be related to the pgadmin image, as the environment variable seems to be properly propagated.

**Comment by bcouetil** [comment]
Hello 😊

The values.yml still says :

```
# can be email or nickname
```

Which is misleading 😊
