### ISSUE TITLE
[pgadmin] Automatically register server provisioned by Zalando operator

### ISSUE THREAD

**Issue by JarnoRFB** [rowanruseler/helm-charts#51]
**Is your feature request related to a problem? Please describe.**
Hi and thanks a lot for maintaining this chart!
I am provisioning a postgres cluster with the zalando operator. I could already successfully connect to the database using the service name as host, and the password extracted from the secret created by the operator.

As the setup is probably going to be deployed a lot of times for short lived review instance, I would like to automatically register the server with pgadmin. I saw that it was possible using `serverDefinitions`. That helps a lot, because I can set up a server there and the user than only has to supply the password, which one has to manually extract from the secret. 
As for the server definition, it seems only possible to pass a reference to a pgpass file there, but not directly to a secret.

**Describe the solution you'd like**
At best I would of course like to simply pass the name of the postgres resource and have the rest be figured out be some logic in the chart, or maybe by some operator.

For the shorter term, I would simply like know whether there is a good way to automatically pass the credentials generated by the postgres operator to pgadmin.

**Comment by rowanruseler** [comment]
Good question, sadly I do not have a solution for you.
