### ISSUE TITLE
[pgAdmin4] Provide information to install pgAgent

### ISSUE THREAD

**Issue by RicardoHS** [rowanruseler/helm-charts#53]
Include information on how to install pgAgent along with the chart.

Since the image does not include any package manager or tools like gcc, I don't see how it is possible to install pgAgent even after the pod has been deployed.

Please include information on how to do this. Thank you.

**Comment by rowanruseler** [comment]
Feel free to open a pull request, I do not use pgAgent and currently I do not have the time to set this up.
