### ISSUE TITLE
Cannot instantiate server definitions

### ISSUE THREAD

**Issue by evgenysavostyanov** [rowanruseler/helm-charts#64]
Hello @rowanruseler,

I am to set up a new postgres database and pgadmin4 with the server definition in minikube, so that pgadmin loads that server definition on startup and I don't have to add it manually on every next launch. I have configured the following in values.yaml:

```
serverDefinitions:
  ## If true, server definitions will be created
  ##
  enabled: true

  servers: |-
  "1": {
  "Name": "My Server",
  "Group": "MyServers",
  "Port": 30066,
  "Username": "admin@admin.com",
  "Host": 172.17.0.2,
  "SSLMode": "prefer",
  "MaintenanceDB": "postgres"
    }
```
This does not work for me, I tried to delete the database with persistent volume and create it over again, but still this definition does not get picked up. Also, I noticed that the port for the postgres service is dynamic and changes on every next startup, e.g. from 5432:30011 to 5432:30066. I tried to set 5432 as static "Port" value there, but this did not work out either.
What am I doing wrong? Please, provide your suggestions.

**Comment by evgenysavostyanov** [comment]
Can I get an answer, please?

**Comment by rowanruseler** [comment]
I do not think you are doing anything wrong, I just think this is broken in the image itself. I need some time to investigate this issue and a few others but sadly I am not in the position to spend any time on it yet.

Hopefully I am able to resolve or at least pin point this issue soon.

**Comment by rowanruseler** [comment]
Just tested it myself, and got it to work in the latest version
![Screenshot from 2021-03-04 13-24-00](https://user-images.githubusercontent.com/29372016/109963939-4912e300-7ced-11eb-8a3b-565146b51235.png)

Instead of `"Host": 172.17.0.2,`, I used HostAddr: - Perhaps this is why it is failing for you?

**Comment by rowanruseler** [comment]
Tested it, and also worked with Host - Can you try again? With the latest version - maybe you made a typo somewhere in your configuration?

**Comment by evgenysavostyanov** [comment]
I upgraded to 5.0, tried both ways, no server definitions get loaded. Not sure how to proceed...

**Comment by evgenysavostyanov** [comment]
@rowanruseler, would be great if you share your values.yaml server definitions configuration with blurred credentials, so that I compare it with mine? Thank you!

**Comment by rowanruseler** [comment]
```
VolumePermissions:
  enabled: true

serverDefinitions:
  enabled: true

  servers: |-
    "1": {
      "Name": "Primary c001",
      "Group": "Primary",
      "Port": 5432,
      "Username": "postgres",
      "Host": "192.168.1.1",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    },
    "2": {
      "Name": "Primary c002",
      "Group": "Primary",
      "Port": 5432,
      "Username": "postgres",
      "Host": "192.168.1.1",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    },
    "3": {
      "Name": "Primary c003",
      "Group": "Primary",
      "Port": 5432,
      "Username": "postgres",
      "Host": "192.168.1.1",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    },
    "4": {
      "Name": "Replication c001",
      "Group": "Replication",
      "Port": 5432,
      "Username": "postgres",
      "Host": "192.168.1.1",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    },
    "5": {
      "Name": "Replication c002",
      "Group": "Replication",
      "Port": 5432,
      "Username": "postgres",
      "Host": "192.168.1.1",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    },
    "6": {
      "Name": "Replication c003",
      "Group": "Replication",
      "Port": 5432,
      "Username": "postgres",
      "Host": "192.168.1.1",
      "SSLMode": "prefer",
      "MaintenanceDB": "postgres"
    }
```

**Comment by evgenysavostyanov** [comment]
Well, I tried all possible options. Maybe we could have a screensharing session to resolve it? If not, I guess the issue can be closed with no resolution.

**Comment by rowanruseler** [comment]
@evgenysavostyanov sure, send me an email.

**Comment by evgenysavostyanov** [comment]
@rowanruseler, thanks a lot for the helpful debugging session. 
My issue was in spacing and host api not given in quotes. It works now after these changes!
