### ISSUE TITLE
[pgadmin] Missing feature documentation for .Values.persistentVolume.existingClaim

### ISSUE THREAD

**Issue by cep21** [rowanruseler/helm-charts#74]
This chart value does not appear documented on the README
```
.Values.persistentVolume.existingClaim
```

**Comment by rowanruseler** [comment]
Hi @cep21,

Thanks for pointing that out, you are more then welcome to open a PR with the documentation. Cheers

**Comment by rowanruseler** [comment]
https://github.com/rowanruseler/helm-charts/pull/94
