### ISSUE TITLE
Unable to add LDAP

### ISSUE THREAD

**Issue by avurlerby** [rowanruseler/helm-charts#77]
Hi, 

I successfully deployed this helm chart using a ci/cd pipeline and it was successful. I am also able to add databases.

I tried to enable ldap according to [https://github.com/rowanruseler/helm-charts/issues/47] by adding the following details to the value.yaml env variables:

env:
  variables:
    - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
      value: "['ldap', 'internal']"
    - name: PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
      value: "False"
    - name: PGADMIN_CONFIG_LDAP_CONNECTION_TIMEOUT
      value: 30
    - name: PGADMIN_CONFIG_LDAP_SERVER_URI
      value: "'ldap://ldap.mydomain.com:389'"
    - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
      value: "'dc=mydomain,dc=com'"
    - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
      value: "'UserPrincipalName'"
    - name: PGADMIN_CONFIG_LDAP_BIND_USER
      value: "'myuser'"
    - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
      value: "'mypassword'"

Which generates the following config_distro.py:

HELP_PATH = '../../docs'
DEFAULT_BINARY_PATHS = {
        'pg': '/usr/local/pgsql-12'
}
LDAP_SEARCH_BASE_DN = 'dc=mydomain,dc=com'
LDAP_AUTO_CREATE_USER = False
LDAP_SERVER_URI = 'ldap://ldap.mydomain.com:389'
AUTHENTICATION_SOURCES = ['ldap', 'internal']
ENHANCED_COOKIE_PROTECTION = False
LDAP_USERNAME_ATTRIBUTE = 'UserPrincipalName'
LDAP_BIND_PASSWORD = 'mypassword'
LDAP_CONNECTION_TIMEOUT = 30
LDAP_BIND_USER = 'myuser'

But I still cannot login. Is there anything that I am missing.

Thanks.

**Comment by rowanruseler** [comment]
As you already linked yourself, check outs the solution of https://github.com/rowanruseler/helm-charts/issues/47. Really sorry but I've purged ldap out of my environment years ago so sadly unable to test.

**Comment by manueliglesiasgarcia** [comment]
I believe that you've to put the variable `PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER` as `True` so the internal SQLite Database that It's running inside the PGAdmin pod registers the user automatically

**Comment by avurlerby** [comment]
It

> I believe that you've to put the variable `PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER` as `True` so the internal SQLite Database that It's running inside the PGAdmin pod registers the user automatically

I set the variable PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER as True still didn't work

**Comment by manueliglesiasgarcia** [comment]
I can tell you that for me It's working LDAP using these configurations
```
        - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
          value: ['ldap','internal']
        - name: PGADMIN_CONFIG_LDAP_SERVER_URI
          value: '''ldap://example:389'''
        - name: PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
          value: "True"
        - name: PGADMIN_CONFIG_LDAP_BIND_USER
          value: '''cn=user,ou=Service Accounts,dc=example,dc=com'''
        - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
          value: "'mypassword'"
        - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
          value: '''dc=example,dc=com'''
        - name: PGADMIN_CONFIG_LDAP_BASE_DN
          value: '''dc=example,dc=com'''
        - name: PGADMIN_CONFIG_LDAP_SEARCH_FILTER
          value: '''(objectclass=user)'''
        - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
          value: '''sAMAccountName'''
        - name: PGADMIN_LISTEN_ADDRESS
          value: 0.0.0.0
        - name: PGADMIN_LISTEN_PORT
          value: "80"
```

**Comment by manueliglesiasgarcia** [comment]
> It
> 
> > I believe that you've to put the variable `PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER` as `True` so the internal SQLite Database that It's running inside the PGAdmin pod registers the user automatically
> 
> I set the variable PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER as True still didn't work

I can tell you that for me It's working LDAP using these configurations
```
        - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
          value: ['ldap','internal']
        - name: PGADMIN_CONFIG_LDAP_SERVER_URI
          value: '''ldap://example:389'''
        - name: PGADMIN_CONFIG_LDAP_AUTO_CREATE_USER
          value: "True"
        - name: PGADMIN_CONFIG_LDAP_BIND_USER
          value: '''cn=user,ou=Service Accounts,dc=example,dc=com'''
        - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
          value: "'mypassword'"
        - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
          value: '''dc=example,dc=com'''
        - name: PGADMIN_CONFIG_LDAP_BASE_DN
          value: '''dc=example,dc=com'''
        - name: PGADMIN_CONFIG_LDAP_SEARCH_FILTER
          value: '''(objectclass=user)'''
        - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
          value: '''sAMAccountName'''
        - name: PGADMIN_LISTEN_ADDRESS
          value: 0.0.0.0
        - name: PGADMIN_LISTEN_PORT
          value: "80"
```

**Comment by avurlerby** [comment]
Thanks @manueliglesiasgarcia It works when I added PGADMIN_CONFIG_LDAP_BASE_DN. However, the users cannot view the DBs. Is there any config that's missing?

**Comment by manueliglesiasgarcia** [comment]
No, there's nothing missing, If it's a new user probably they'll need to add the DBs like this
![image](https://user-images.githubusercontent.com/55031066/112180127-2ccedb80-8bf3-11eb-8720-d143bb3098e5.png)
@rowanruseler I believe that this issue can be closed definitely there's not issue that It's related to your Helm chart

**Comment by rowanruseler** [comment]
Thanks @manueliglesiasgarcia, will close this issue indeed. Lets work on the example you created and maybe make minor adjustments to the chart to suit ldap more.

**Comment by avurlerby** [comment]
I have added the db already but the created ldap users can't see the db
