### ISSUE TITLE
[all] is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by webjoel** [rowanruseler/helm-charts#78]
When execute:
```
helm repo add runix https://helm.runix.net/
```
return error:
```
Error: looks like "https://helm.runix.net/" is not a valid chart repository or cannot be reached: Get https://helm.runix.net/index.yaml: dial tcp: lookup helm.runix.net on 127.0.0.53:53: no such host
```
If remove "/" on url, work's fine.

Suggested:

- Change in docs to:
```
helm repo add runix https://helm.runix.net
```

**Comment by rowanruseler** [comment]
@webjoel thanks for reporting the issue.

**Comment by webjoel** [comment]
Sorry, I didn't remember talking about this link to:

https://artifacthub.io/packages/helm/runix/pgadmin4

**Comment by rowanruseler** [comment]
https://github.com/rowanruseler/helm-charts/pull/80/files

My bad, forgot I had it written down at two pages.
