### ISSUE TITLE
[pgadmin4] unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend

### ISSUE THREAD

**Issue by viceice** [rowanruseler/helm-charts#90]
**Describe the bug**
Can't updgrade to newest chart, see error

```
Error: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[1].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[1].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```

**Version of Helm and Kubernetes**: 
Kubernetes: v1.20.4+k3s1
Helm: 2.0.3 ( using Terraform)

**Which chart**: 

pgadmin4 1.5.7 (upgrade from 1.5.6)

**What happened**:
Upgrade fails with error above, i think #89 has broken something

**What you expected to happen**:
Upgrade should succeed.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rowanruseler** [comment]
Hi @viceice, my apologies @Vad1mo created this PR: https://github.com/rowanruseler/helm-charts/pull/89 but it wasn't fully tested it seems from his end. So sloppy mistake from me by merging it without thinking about any version adjustments made.

I am currently not in the state to fix it, but I should be able to resolve this tomorrow.

**Comment by viceice** [comment]
No hurry, i rolled back to previous version for now.

**Comment by viceice** [comment]
Ups, update issue title to reflect the cuase 👼

**Comment by rowanruseler** [comment]
@viceice I found some spare time - did some tests but not fully, could you give it a shot and let me know? https://github.com/rowanruseler/helm-charts/pull/92

Be aware `paths` has an adjustment.

**Comment by viceice** [comment]
Ok, i do not change the `paths` 🙃

**Comment by rowanruseler** [comment]
I am going to close this issue, we are aware that currently v1 is not supported.

So I reverted back to what it kinda was, and a new implementation has to be done, but this time including all fronts.
